"""initial schema

Revision ID: ac102b52a7d6
Revises: 
Create Date: 2026-09-22 13:03:44.512270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac102b52a7d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_reason_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('board_manufacturing', 'printing', 'bundling', name='stage'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('downtime_reason_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('running', 'setup', 'breakdown', 'waiting', 'idle', name='time_category'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('metric_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.String(length=500), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('category', sa.Enum('material', 'throughput', 'quality', 'time', 'parameters', name='metric_category'), nullable=False),
    sa.Column('stage', sa.Enum('board_manufacturing', 'printing', 'bundling', name='stage'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('line_type', sa.Enum('automatic', 'semi_automatic', name='line_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('daily_plant_rollups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('rollup_date', sa.Date(), nullable=False),
    sa.Column('overall_yield_pct', sa.Float(), nullable=True),
    sa.Column('utilization_pct', sa.Float(), nullable=True),
    sa.Column('rate_efficiency_pct', sa.Float(), nullable=True),
    sa.Column('quality_pct', sa.Float(), nullable=True),
    sa.Column('plant_productivity_pct', sa.Float(), nullable=True),
    sa.Column('waste_cost_inr', sa.Float(), nullable=True),
    sa.Column('power_per_tonne_kwh', sa.Float(), nullable=True),
    sa.Column('grid_power_share_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id', 'rollup_date')
    )
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('board_manufacturing', 'printing', 'bundling', name='stage'), nullable=False),
    sa.Column('machine_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rated_speed', sa.Float(), nullable=True),
    sa.Column('rated_speed_unit', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id', 'machine_code')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('ply_construction', sa.String(length=20), nullable=True),
    sa.Column('flute_profile', sa.String(length=10), nullable=True),
    sa.Column('sheet_length_mm', sa.Float(), nullable=True),
    sa.Column('sheet_width_mm', sa.Float(), nullable=True),
    sa.Column('paper_gsm', sa.Float(), nullable=True),
    sa.Column('paper_bf', sa.Float(), nullable=True),
    sa.Column('quantity_ordered', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('standard_speed', sa.Float(), nullable=True),
    sa.Column('standard_speed_unit', sa.String(length=20), nullable=True),
    sa.Column('order_complete_staged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id', 'order_number')
    )
    op.create_table('plant_metric_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('metric_definition_id', sa.Integer(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['metric_definition_id'], ['metric_definitions.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id', 'metric_definition_id', 'effective_from')
    )
    op.create_table('power_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('grid', 'dg', name='power_source'), nullable=False),
    sa.Column('kwh', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('shift_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('scheduled_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id', 'shift_date', 'shift_number')
    )
    op.create_table('machine_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bundling_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_run_id', sa.Integer(), nullable=False),
    sa.Column('worker_count', sa.Integer(), nullable=False),
    sa.Column('bundles_count', sa.Integer(), nullable=False),
    sa.Column('output_kg', sa.Float(), nullable=True),
    sa.Column('count_accuracy_pct', sa.Float(), nullable=True),
    sa.Column('starvation_minutes', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_run_id'], ['machine_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_run_id')
    )
    op.create_table('material_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_run_id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.Enum('kraft_paper', 'board', 'ink', 'starch', name='material_type'), nullable=False),
    sa.Column('input_qty', sa.Float(), nullable=False),
    sa.Column('output_qty', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_run_id'], ['machine_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parameter_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('machine_run_id', sa.Integer(), nullable=True),
    sa.Column('metric_definition_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('plc_live', 'qa_sample', 'manual', name='parameter_source'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['machine_run_id'], ['machine_runs.id'], ),
    sa.ForeignKeyConstraint(['metric_definition_id'], ['metric_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_run_id', sa.Integer(), nullable=False),
    sa.Column('good_qty', sa.Float(), nullable=False),
    sa.Column('reject_qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_run_id'], ['machine_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_run_id')
    )
    op.create_table('time_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_run_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('running', 'setup', 'breakdown', 'waiting', 'idle', name='time_category'), nullable=False),
    sa.Column('reason_code_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_run_id'], ['machine_runs.id'], ),
    sa.ForeignKeyConstraint(['reason_code_id'], ['downtime_reason_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defect_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quality_record_id', sa.Integer(), nullable=False),
    sa.Column('reason_code_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quality_record_id'], ['quality_records.id'], ),
    sa.ForeignKeyConstraint(['reason_code_id'], ['defect_reason_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('defect_observations')
    op.drop_table('time_logs')
    op.drop_table('quality_records')
    op.drop_table('parameter_readings')
    op.drop_table('material_flows')
    op.drop_table('bundling_records')
    op.drop_table('machine_runs')
    op.drop_table('shifts')
    op.drop_table('power_readings')
    op.drop_table('plant_metric_targets')
    op.drop_table('orders')
    op.drop_table('machines')
    op.drop_table('daily_plant_rollups')
    op.drop_table('plants')
    op.drop_table('metric_definitions')
    op.drop_table('downtime_reason_codes')
    op.drop_table('defect_reason_codes')
    # ### end Alembic commands ###
