"""add lineal_metres to machine_runs

Revision ID: fd5a50657702
Revises: c0a6ff5c40f2
Create Date: 2026-09-22 13:19:10.456149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd5a50657702'
down_revision: Union[str, Sequence[str], None] = 'c0a6ff5c40f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine_runs', sa.Column('lineal_metres', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine_runs', 'lineal_metres')
    # ### end Alembic commands ###
